version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - KAFKA_BROKERS=${KAFKA_BROKERS:-localhost:9092}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
    volumes:
      - ./backend/.env:/app/.env:ro
      - backend_logs:/app/logs
      - backend_sessions:/app/sessions
      - backend_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4001
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_logs:
  backend_sessions:
  backend_data: